steps:
  # Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/gcpdevops', '.']
  
  # Push the container image tp the artifact registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/gcpdevops']
  
  # Deploy the container image to the GKE
- name: 'gcr.io/cloud-builders/gcp-project-kodekloud'
  args:
  - run
  - --filename=gke.yaml
  - --image=gcr.io/$PROJECT_ID/gcpdevops
  - --location=us-centeral1-c
  - --cluster=devops-project
  - --namespace=gcp-devops-prod
